# The west manifest file for the Pinetime.
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west.
#
# You can create your own manifest files and put them in any
# repository you want, to create your own custom Pinetime installation.
# For example, you could create a manifest file in your own
# out-of-tree application directory, which would pull the pinetime repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new pinetime installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: pinetime

  remotes:
    - name: pinetime
      url-base: https://github.com/zephyrproject-rtos

  # The list of external projects for the Pinetime.
  #
  projects:
    - name: cmsis
      path: modules/hal/cmsis
      revision: 542b2296e6d515b265e25c6b7208e8fea3014f90
    - name: hal_nordic
      path: modules/hal/nordic
      revision: 00580f43b9d48f2079d611ce12f0fbc78d3040f1
    - name: lvgl
      path: modules/lib/gui/lvgl
      revision: 74fc2e753a997bd71cefa34dd9c56dcb954b42e2
    - name: segger
      path: modules/debug/segger
      revision: 6fcf61606d6012d2c44129edc033f59331e268bc
    - name: tinycrypt
      path: modules/crypto/tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: 27d42f060da1afe129ae2b66e15a09dc54e904cf
  self:
    path: pinetime
